package test.generator.model.person;

import java.util.Date;

public class Address {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column Person.Address.AddressID
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    private Integer addressid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column Person.Address.AddressLine1
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    private String addressline1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column Person.Address.AddressLine2
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    private String addressline2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column Person.Address.City
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    private String city;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column Person.Address.StateProvinceID
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    private Integer stateprovinceid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column Person.Address.PostalCode
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    private String postalcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column Person.Address.rowguid
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    private String rowguid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column Person.Address.ModifiedDate
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    private Date modifieddate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column Person.Address.AddressID
     *
     * @return the value of Person.Address.AddressID
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column Person.Address.AddressID
     *
     * @param addressid the value for Person.Address.AddressID
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column Person.Address.AddressLine1
     *
     * @return the value of Person.Address.AddressLine1
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public String getAddressline1() {
        return addressline1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column Person.Address.AddressLine1
     *
     * @param addressline1 the value for Person.Address.AddressLine1
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1 == null ? null : addressline1.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column Person.Address.AddressLine2
     *
     * @return the value of Person.Address.AddressLine2
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public String getAddressline2() {
        return addressline2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column Person.Address.AddressLine2
     *
     * @param addressline2 the value for Person.Address.AddressLine2
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2 == null ? null : addressline2.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column Person.Address.City
     *
     * @return the value of Person.Address.City
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column Person.Address.City
     *
     * @param city the value for Person.Address.City
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column Person.Address.StateProvinceID
     *
     * @return the value of Person.Address.StateProvinceID
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public Integer getStateprovinceid() {
        return stateprovinceid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column Person.Address.StateProvinceID
     *
     * @param stateprovinceid the value for Person.Address.StateProvinceID
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public void setStateprovinceid(Integer stateprovinceid) {
        this.stateprovinceid = stateprovinceid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column Person.Address.PostalCode
     *
     * @return the value of Person.Address.PostalCode
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column Person.Address.PostalCode
     *
     * @param postalcode the value for Person.Address.PostalCode
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column Person.Address.rowguid
     *
     * @return the value of Person.Address.rowguid
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public String getRowguid() {
        return rowguid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column Person.Address.rowguid
     *
     * @param rowguid the value for Person.Address.rowguid
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid == null ? null : rowguid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column Person.Address.ModifiedDate
     *
     * @return the value of Person.Address.ModifiedDate
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public Date getModifieddate() {
        return modifieddate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column Person.Address.ModifiedDate
     *
     * @param modifieddate the value for Person.Address.ModifiedDate
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
}