package test.generator.dao.person;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;
import test.generator.model.person.Address;
import test.generator.model.person.AddressExample;

public class AddressDAOImpl implements AddressDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public AddressDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public void setSqlMapClient(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public SqlMapClient getSqlMapClient() {
        return sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public int countByExample(AddressExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("Person_Address.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public int deleteByExample(AddressExample example) throws SQLException {
        int rows = sqlMapClient.delete("Person_Address.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public int deleteByPrimaryKey(Integer addressid) throws SQLException {
        Address key = new Address();
        key.setAddressid(addressid);
        int rows = sqlMapClient.delete("Person_Address.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public void insert(Address record) throws SQLException {
        sqlMapClient.insert("Person_Address.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public void insertSelective(Address record) throws SQLException {
        sqlMapClient.insert("Person_Address.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public List selectByExample(AddressExample example) throws SQLException {
        List list = sqlMapClient.queryForList("Person_Address.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public Address selectByPrimaryKey(Integer addressid) throws SQLException {
        Address key = new Address();
        key.setAddressid(addressid);
        Address record = (Address) sqlMapClient.queryForObject("Person_Address.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public int updateByExampleSelective(Address record, AddressExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("Person_Address.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public int updateByExample(Address record, AddressExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("Person_Address.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public int updateByPrimaryKeySelective(Address record) throws SQLException {
        int rows = sqlMapClient.update("Person_Address.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    public int updateByPrimaryKey(Address record) throws SQLException {
        int rows = sqlMapClient.update("Person_Address.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    private static class UpdateByExampleParms extends AddressExample {
        private Object record;

        public UpdateByExampleParms(Object record, AddressExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}