package test.generator.dao.person;

import java.sql.SQLException;
import java.util.List;
import test.generator.model.person.Address;
import test.generator.model.person.AddressExample;

public interface AddressDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    int countByExample(AddressExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    int deleteByExample(AddressExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    int deleteByPrimaryKey(Integer addressid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    void insert(Address record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    void insertSelective(Address record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    List selectByExample(AddressExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    Address selectByPrimaryKey(Integer addressid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    int updateByExampleSelective(Address record, AddressExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    int updateByExample(Address record, AddressExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    int updateByPrimaryKeySelective(Address record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table Person.Address
     *
     * @ibatorgenerated Tue Sep 07 17:48:31 CST 2010
     */
    int updateByPrimaryKey(Address record) throws SQLException;
}